
spring:
  profile:
    active: local
server:
  port: 9091

---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Movie_Info_Service

---
spring:
  config:
    activate:
      on-profile:
        - local

  data:
    mongodb:
      host: localhost
      port: 27017
      database:  local

---

spring:
  config:
    activate:
      on-profile:
        - non-prod

  data:
    mongodb:
      host: localhost
      port: 27017
      database:  local

---

spring:
  config:
    activate:
      on-profile:
        - prod

  data:
    mongodb:
      host: localhost
      port: 27017
      database:  local
